name: ADA Handle NodeJS App Deploy

on:
  push:
    branches: [ develop, master ]
jobs:
  dispatch-testnet:
    if: ${{github.ref == 'refs/heads/develop'}}
    name: Dispatch to Deployments
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          MESSAGE=${{ toJson(github.event.head_commit.message) }}
      - name: Trigger Workflow Dispatch Event for TestNet
        run: |
          curl -XPOST -u "${{secrets.DEPLOYMENT_ACCESS_USERNAME}}:${{secrets.DEPLOYMENT_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/koralabs/adahandle-deployments/actions/workflows/minting-engine.yml/dispatches \
          --data '{"ref": "master", "inputs": { "branch_to_deploy":"develop", "network":"TESTNET", "commit_sha":"${{ github.sha }}", "commit_url": "${{ github.event.head_commit.url }}", "commit_message": "See commit above", "hard_reset": "false" }}'
  dispatch-mainnet:
    if: ${{github.ref == 'refs/heads/master'}}
    name: Dispatch to Deployments
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          MESSAGE=${{ toJson(github.event.head_commit.message) }}
      - name: Trigger Workflow Dispatch Event for MainNet
        run: |
          curl -XPOST -u "${{secrets.DEPLOYMENT_ACCESS_USERNAME}}:${{secrets.DEPLOYMENT_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/koralabs/adahandle-deployments/actions/workflows/minting-engine.yml/dispatches \
          --data '{"ref": "master", "inputs": { "branch_to_deploy":"master", "network":"MAINNET", "commit_sha":"${{ github.sha }}", "commit_url": "${{ github.event.head_commit.url }}", "commit_message": "See commit above", "hard_reset": "false" }}'
